- package.json
- yarn.lock
> chore: bump version to 1.4.2

- .bacon.yml
- .eslintignore
- .eslintrc.js
- .gitignore
- .travis.yml
- index.js
- package.json
- scripts/build.js
- scripts/lint.sh
- scripts/publish.sh
- scripts/setup.sh
- scripts/unit.sh
- yarn.lock
Issue Number: 318933
Adds build scripts for bacon.
Adds lint
Builds/publish from "dist" folder
https://bacon-go.aue1e.saasure.net/#!/commits/okta-react-native
> lint/build/test/publish (on bacon)

- CHANGELOG.md
- android/build.gradle
> chore: upgrade android oidc dep - OKTA-316020

- scripts/publish.sh
> Publish to npm-topic

- OktaSdkBridgeReactNative.podspec
There is an EEP ticket: https://oktainc.atlassian.net/browse/OKTA-336612?oldIssueView=true
This issue is caused by recent development in OIDC SDK, so point to the previous version can temporarily solve this problem.
@shuowu-okta @IldarAbdullin-okta
> Point to OIDC 3.8.0

- CHANGELOG.md
- package.json
> adds bump for 1.4.3

- OktaSdkBridgeReactNative.podspec
> Point to OIDC 3.9.2

- CHANGELOG.md
- OktaSdkBridgeReactNative.podspec
- package.json
> release 1.4.4

- CHANGELOG.md
- package.json
> set master package version to 1.5.0

- README.md
- android/build.gradle
> Update minSdk and related documentation.

- android/src/main/java/com/oktareactnative/OktaSdkBridgeModule.java
- ios/OktaSdkBridge.swift
https://github.com/okta/okta-react-native/issues/61
Issue Number: OKTA-364065
Behavior now in tact with documentation
https://github.com/okta/okta-react-native#getaccesstoken
> getAccessToken promise rejection fix

- package.json
> chore: 1.9.2 version bump

- CHANGELOG.md
> chore: Updates changelog for 1.9.3

- CHANGELOG.md
> chore: Updates Changelog

- CHANGELOG.md
> Update changelog 1.11.1

- CHANGELOG.md
- types/index.d.ts
- types/index.test-d.ts
> Version 1.12.1 backport

- android/src/main/java/com/oktareactnative/OktaSdkBridgeModule.java
> Fixes react native sign in results

- CHANGELOG.md
> Updates android changelog

- CHANGELOG.md
> Fixes typo changelog

- CHANGELOG.md
> Updates react native changelog

- android/src/main/java/com/oktareactnative/OktaSdkBridgeModule.java
- package.json
> OKTA-428171 Backport activity result fix to 1.13.x

- CHANGELOG.md
- android/src/main/java/com/oktareactnative/OktaSdkBridgeModule.java
- package.json
> Fix sessionClient being null when not calling signIn

- CHANGELOG.md
- ios/Podfile.lock
- ios/ReactNativeOktaSdkBridge.xcodeproj/project.pbxproj
> Update OktaOidc to 3.11.7

- .circleci/config.yml
- .github/workflows/okta-react-native.yml
This PR fixes snyk scan. A successful scan can be seen here: https://github.com/okta/okta-react-native/pull/443
> Fix snyk scan
